image: rust

definitions:
  caches:
    cargo: /usr/local/cargo
    rust-target: $BITBUCKET_CLONE_DIR/target
    rustup-nightly: /usr/local/rustup/nightly-x86_64-unknown-linux-gnu

pipelines:
  branches:
    master:
      - step: 
          caches:
            - cargo
            - rust-target
            - rustup-nightly

          script:
            - echo "Build project"                    ; cargo build --release
            - echo "Format source code"               ; ./scripts/fmt.sh
            - echo "Run Clippy"                       ; ./scripts/clippy.sh
            - echo "Run cargo-deny"                   ; ./scripts/deny.sh
            - echo "Run unit tests"                   ; cargo test --lib --release -v --no-fail-fast
            - echo "Run integration tests"            ; cargo test --test '*' --release -v --no-fail-fast

  pull-requests:
    '**':
      - step: 
          caches:
            - cargo
            - rust-target
            - rustup-nightly

          script:
            - echo "Build project"                    ; cargo build --release
            - echo "Format source code"               ; ./scripts/fmt.sh
            - echo "Run Clippy"                       ; ./scripts/clippy.sh
            - echo "Run cargo-deny"                   ; ./scripts/deny.sh
            - echo "Run unit tests"                   ; cargo test --lib --release -v --no-fail-fast
            - echo "Run integration tests"            ; cargo test --test '*' --release -v --no-fail-fast
